# Q1

두 정수 A와 B를 입력받은 다음, A-B를 출력하는 프로그램을 작성하시오.

입력 : 3 2  
출력 : 1

In [0]:
def subtraction(a, b):
  return a - b

a, b = map(int, input('두 정수를 입력하세요: ').split())

answer = subtraction(a, b)

print(answer)

두 정수를 입력하세요: 3 2
1

In [0]:
ans = 1
if (answer == ans):
    print("정답입니다!!!!")
else:
    raise ValueError(f"{ans}가 나와야합니다. 다시 확인해주세요!")

정답입니다!!!!


# Q2

ACM-ICPC 인터넷 예선, Regional, 그리고 World Finals까지 이미 2회씩 진출해버린 kriii는 미련을 버리지 못하고 왠지 모르게 올 해에도 파주 World Finals 준비 캠프에 참여했다. 대회를 뜰 줄 모르는 지박령 kriii를 위해서 격려의 문구를 출력해주자.

입력 : 

출력 : '힘내라 친구'

In [0]:
# 문제에서 입력이 공백으로 처리되어 있어 공백일 경우로 분기 처리함.
temp = input()

if (temp == ''):
  answer = '힘내라 친구'
  print(answer)

힘내라 친구

In [0]:
ans = '힘내라 친구'
if (answer == ans):
    print("정답입니다!!!!")
else:
    raise ValueError(f"{ans}가 나와야합니다. 다시 확인해주세요!")

정답입니다!!!!

# Q3

문제 두 자연수 A와 B가 주어진다. 이때, A+B, A-B, A*B, A/B(몫), A%B(나머지)를 출력하는 프로그램을 작성하시오.


조건 : 
- class Calculator를 선언 해주세요.
- +, - , *, / 은 모두 magic method 로 만드세요.

In [0]:
class Calculator:
  def __init__(self):
    self.result = 0
  def __add__(self, a, b):
    self.result = a + b
    print('A + B = {}'.format(self.result))
  def __sub__(self, a, b):
    self.result = a - b
    print('A - B = {}'.format(self.result))
  def __mul__(self, a, b):
    self.result = a * b
    print('A % B = {}'.format(self.result))
  def __truediv__(self, a, b):
    self.result = a / b
    print('A / B = {}'.format(self.result))
  def __mod__(self, a, b):
    self.result = a % b
    print('A % B = {}'.format(self.result))

a, b = map(int, input('두 자연수를 입력하세요: ').split())
cal = Calculator()
cal.__add__(a, b)
cal.__sub__(a, b)
cal.__mul__(a, b)
cal.__truediv__(a, b)
cal.__mod__(a, b)

두 자연수를 입력하세요: 4 2
A + B = 6
A - B = 2
A % B = 8
A / B = 2.0
A % B = 0

In [0]:
calc = Calculator()
if (answer == ans):
    print("정답입니다!!!!")
else:
    raise ValueError(f"{ans}가 나와야합니다. 다시 확인해주세요!")

정답입니다!!!!

# Q4

영어 대소문자와 띄어쓰기만으로 이루어진 문자열이 주어진다. 이 문자열에는 몇 개의 단어가 있을까? 이를 구하는 함수(count_words)를 작성하시오. 

입력

The Curious Case of Benjamin Button 

출력

6

입력

Mazatneunde Wae Teullyeoyo

출력

3

입력

Teullinika Teullyeotzi

출력

2

In [0]:
def count_words(str_text):
  return len(str_text.split(' '))

In [0]:
l = ['The Curious Case of Benjamin Button', 'Mazatneunde Wae Teullyeoyo', 'Teullinika Teullyeotzi']
if list(map(count_words, l)) == [6, 3, 2]:
    print("정답입니다!!!!")
else:
    raise ValueError("다시 확인해주세요!")

정답입니다!!!!

# Q5

"OOXXOXXOOO"와 같은 OX퀴즈의 결과가 있다.<br>
 O는 문제를 맞은 것이고, X는 문제를 틀린 것이다. <br>
 문제를 맞은 경우 그 문제의 점수는 그 문제까지 연속된 O의 개수가 된다. <br><br>

 "OOXXOXXOOO"의 점수는 1+2+0+0+1+0+0+1+2+3 = 10점이다.<br>
OX퀴즈의 결과가 주어졌을 때, 점수를 구하는 함수(calc_score)를 작성하시오.<br><br>

입력

OOXXOXXOOO

출력 

10

입력

OOXXOOXXOO

출력 

9

입력

OXOXOXOXOXOXOX

출력 

7

입력

OOOOOOOOOO

출력 

55

입력

OOOOXOOOOXOOOOX

출력 

30

In [0]:
def calc_score(inputs_item):
  score = 0
  temp_list = list(inputs_item)
  score_list = []
  
  for i in range(len(temp_list)):
    if (temp_list[i] == 'O'):     
      score += 1
    else:
      score = 0
    
    score_list.append(score)
  
  print(score_list)
  
  return sum(score_list)

# 검증을 위한 코드
inputs = ['OOXXOXXOOO', 'OOXXOOXXOO', 'OXOXOXOXOXOXOX', 'OOOOOOOOOO', 'OOOOXOOOOXOOOOX']
outputs = []

for i in range(len(inputs)):
  outputs.append(calc_score(inputs[i]))
  
print(outputs)

[1, 2, 0, 0, 1, 0, 0, 1, 2, 3]
[1, 2, 0, 0, 1, 2, 0, 0, 1, 2]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0]
[10, 9, 7, 55, 30]

In [0]:
inputs = ['OOXXOXXOOO', 'OOXXOOXXOO', 'OXOXOXOXOXOXOX', 'OOOOOOOOOO', 'OOOOXOOOOXOOOOX']
outputs = [10, 9, 7, 55, 30]

if list(map(calc_score, inputs)) == outputs:
    print("정답입니다!!!!")
else:
    raise ValueError("다시 확인해주세요!")

[1, 2, 0, 0, 1, 0, 0, 1, 2, 3]
[1, 2, 0, 0, 1, 2, 0, 0, 1, 2]
[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0]
정답입니다!!!!



# Q6
문제<br>
리스트 l과 정수 x가 주어진다. 이때, l에서 x보다 작은 수를 모두 출력하는 함수(print_less)를 작성하시오.<br>

입력<br>

l : [ 1 10 4 9 2 3 8 5 7 6 ]

x : 5

출력<br>

[1 4 2 3 ]

In [0]:
# 문제에서 함수(print_less)안에서 출력을 실행하라는 조건을 준 것으로 이해함.
# 그래서 따로 print_less 안에서 list에 저장하거나 하지 않고 바로 출력을 실행함.

lst = input('l: ').split()
comparision = input('x: ')

def print_less(i):
  if(int(i) < int(comparision)):
    print(i, end=' ')
    
for i in range(len(lst)):
  print_less(lst[i])

l: 1 10 4 9 2 3 8 5 7 6
x: 5
1 4 2 3




# Q7

문제

배열을 정렬하는 것은 쉽다. 수가 주어지면, 그 수의 각 자리수를 내림차순으로 정렬해보자.

입력

첫째 줄에 정렬하고자하는 수 N이 주어진다. N은 1,000,000,000보다 작거나 같은 자연수이다.

출력

첫째 줄에 자리수를 내림차순으로 정렬한 수를 출력한다.

입력

'2143'

출력 <br>

'4321' <br>

In [0]:
number = input()

if (int(number) < 0 or int(number) > 1000000000):
  print('1000000000 보다 작은 자연수를 입력하세요.')
else: 
  lst = [i for i in number]
  lst.sort(reverse=True)
  print(''.join(lst))

2143
4321




# Q8

문제

어떤 양의 정수 X의 자리수가 등차수열을 이룬다면, 그 수를 한수라고 한다. 등차수열은 연속된 두 개의 수의 차이가 일정한 수열을 말한다. N이 주어졌을 때, 1보다 크거나 같고, N보다 작거나 같은 한수의 개수를 출력하는 프로그램을 작성하시오.

입력

첫째 줄에 1,000보다 작거나 같은 자연수 N이 주어진다.

출력
첫째 줄에 1보다 크거나 같고, N보다 작거나 같은 한수의 개수를 출력한다.

입력

110

출력

99

In [0]:
hansu_count = 0
input_number = int(input())

def check_hansu(input_number):
  result = False
  
  number_list = [int(i) for i in [*str(input_number)]]
  
  if (len(number_list) <= 2):
    result = True
  else:
    first_common_difference = number_list[1] - number_list[0]
    
    for i in range(0, len(number_list) - 1):
      common_difference = number_list[i + 1] - number_list[i]
      
      if first_common_difference != common_difference:
        result = False
        break
      else:
        result = True
          
  return result

for i in range(1, input_number + 1):
  if (check_hansu(i)):
    hansu_count += 1

print(hansu_count)

110
99