# Q1

두 정수 A와 B를 입력받은 다음, A-B를 출력하는 프로그램을 작성하시오.

입력 : 3, 2  
출력 : 1

In [0]:
# code here
A, B = map(int, input().split())
answer = A - B

3 2

In [0]:
ans = 1
if (answer == ans):
    print("정답입니다!!!!")
else:
    raise ValueError(f"{ans}가 나와야합니다. 다시 확인해주세요!")

정답입니다!!!!


# Q2

ACM-ICPC 인터넷 예선, Regional, 그리고 World Finals까지 이미 2회씩 진출해버린 kriii는 미련을 버리지 못하고 왠지 모르게 올 해에도 파주 World Finals 준비 캠프에 참여했다. 대회를 뜰 줄 모르는 지박령 kriii를 위해서 격려의 문구를 출력해주자.

입력 : 

출력 : '힘내라 친구'

In [0]:
# code here
answer = "힘내라 친구"

In [0]:
ans = '힘내라 친구'
if (answer == ans):
    print("정답입니다!!!!")
else:
    raise ValueError(f"{ans}가 나와야합니다. 다시 확인해주세요!")

정답입니다!!!!

# Q3

문제 두 자연수 A와 B가 주어진다. 이때, A+B, A-B, A*B, A/B(몫), A%B(나머지)를 계산하는 Class를 작성하시오.


조건 : 
```python3
class Calculator:
        def __init__(self, number):
                self.number = number
```
를 선언 해주세요.

- +, - , *, / 은 모두 magic method 로 만드세요.

In [0]:
# code here
class Calculator(object):
    def __add__(a,b):
        print('A+B = {}'.format(a+b))
    def __sub__(a,b):
        print('A-B = {}'.format(a-b))
    def __mul__(a,b):
        print('A*B = {}'.format(a*b))
    def __div__(a,b):
        print('A/B = {}'.format(a/b))
    def __mod__(a,b):
        print('A%B = {}'.format(a%b))

In [0]:
assert 'Calculator' in globals(), "클래스 명을 Calculator로 해주세요"

a = 5
b = 2

x = Calculator(5)
y = Calculator(2)
_add = x + y
_sub = x - y
_mul = x * y
_truediv = x / y
_mod = x % y

assert _add == a+b,(
    f"{a+b}이 되어야 합니다.")
assert _sub == a-b,(
    f"{a-b}이 되어야 합니다.")
assert _mul == a*b,(
    f"{a*b}이 되어야 합니다.")
assert _truediv == a/b,(
    f"{a/b}이 되어야 합니다.")
assert _mod == a%b,(
    f"{a%b}이 되어야 합니다.")


print("정답입니다!!")

TypeError: ignored

# Q4

영어 대소문자와 띄어쓰기만으로 이루어진 문자열이 주어진다. 이 문자열에는 몇 개의 단어가 있을까? 이를 구하는 함수(count_words)를 작성하시오. 

입력

The Curious Case of Benjamin Button 

출력

6

입력

Mazatneunde Wae Teullyeoyo

출력

3

입력

Teullinika Teullyeotzi

출력

2

In [0]:
# code here
def count_words(string):
  words = string.split(" ")
  return len(words)

In [0]:
l = ['The Curious Case of Benjamin Button', 'Mazatneunde Wae Teullyeoyo', 'Teullinika Teullyeotzi']
if list(map(count_words, l)) == [6, 3, 2]:
    print("정답입니다!!!!")
else:
    raise ValueError("다시 확인해주세요!")

정답입니다!!!!

# Q5

"OOXXOXXOOO"와 같은 OX퀴즈의 결과가 있다.<br>
 O는 문제를 맞은 것이고, X는 문제를 틀린 것이다. <br>
 문제를 맞은 경우 그 문제의 점수는 그 문제까지 연속된 O의 개수가 된다. <br><br>

 "OOXXOXXOOO"의 점수는 1+2+0+0+1+0+0+1+2+3 = 10점이다.<br>
OX퀴즈의 결과가 주어졌을 때, 점수를 구하는 함수(calc_score)를 작성하시오.<br><br>

입력

OOXXOXXOOO

출력 

10

입력

OOXXOOXXOO

출력 

9

입력

OXOXOXOXOXOXOX

출력 

7

입력

OOOOOOOOOO

출력 

55

입력

OOOOXOOOOXOOOOX

출력 

30

In [0]:
# code here
def calc_score(result):
  score = 0
  final_score = 0
  for i in range(0,len(result)):
    if result[i]== "O":
      score = score + 1
      final_score = final_score + score 
    else :
      score = 0
    i = i+1  
  return final_score

In [0]:
inputs = ['OOXXOXXOOO', 'OOXXOOXXOO', 'OXOXOXOXOXOXOX', 'OOOOOOOOOO', 'OOOOXOOOOXOOOOX']
outputs = [10, 9, 7, 55, 30]

if list(map(calc_score, inputs)) == outputs:
    print("정답입니다!!!!")
else:
    raise ValueError("다시 확인해주세요!")

정답입니다!!!!



# Q6
문제<br>
리스트 l과 정수 x가 주어진다. 이때, l에서 x보다 작은 수를 모두 출력하는 함수(print_less)를 작성하시오.<br>

입력<br>

l : [ 1 10 4 9 2 3 8 5 7 6 ]

x : 5

출력<br>

[1 4 2 3 ]

In [0]:
# code here
def print_less(I, x):
  list = []
  for i in range(0, len(I)):
    if I[i] < x :
      list.append(I[i])
      i = i+1 
  return list

In [2]:
I = list(map(int, input().split()))
x  = int(input())

print_less(I, x)

1 10 4 9 2 3 8 5 7 6
5

[1, 4, 2, 3]




# Q7

문제

배열을 정렬하는 것은 쉽다. 수가 주어지면, 그 수의 각 자리수를 내림차순으로 정렬해보자.

입력

첫째 줄에 정렬하고자하는 수 N이 주어진다. N은 1,000,000,000보다 작거나 같은 자연수이다.

출력

첫째 줄에 자리수를 내림차순으로 정렬한 수를 출력한다.

입력

'2143'

출력 <br>

'4321' <br>

In [0]:
# code here
list =[]
input = '2143'


for i in range(0, len(input)):
  list.append(input[i])
  i= i+1
  
  
list.sort(reverse=True)
"".join(list)

'4321'

In [0]:
list = [2,1,4,3]
list.sort(reverse=True)
list

[4, 3, 2, 1]




# Q8

문제

어떤 양의 정수 X의 자리수가 등차수열을 이룬다면, 그 수를 한수라고 한다. 등차수열은 연속된 두 개의 수의 차이가 일정한 수열을 말한다. N이 주어졌을 때, 1보다 크거나 같고, N보다 작거나 같은 한수의 개수를 출력하는 프로그램을 작성하시오.

예) 42에서 4, 2는 -2가 등차인 한수다. 123에서 1, 2, 3은 1이 등차인 한수다.

입력

첫째 줄에 1,000보다 작거나 같은 자연수 N이 주어진다.

출력
첫째 줄에 1보다 크거나 같고, N보다 작거나 같은 한수의 개수를 출력한다.

입력

110

출력

99

In [0]:
# code here


input = 110
count = 0 
result =[]

for i in range(1, input+1):
  if i>0 and i<100:
    count = count + 1
    continue 
    
  elif i>=100 and i<=999: 
    s = str(i)
    for j in range(len(s)):
        result.append(s[j])
        j = j+1
    if abs(int(result[0])- int(result[1])) == abs(int(result[1])- int(result[2])):
            count = count + 1    
    i = i+1

count

99

9
0
9
1
9
2

In [0]:
result = []
count = 0 
s = str(999)
for i in range(len(s)):
    result.append(s[i])
    print(s[i])
    print(i)
    i = i+1